/*
 * This file is automatically generated. DO NOT modify it manually.
 *
 * network: goerli
 */

export const Linguo_de_en = "0xDDFac50f2f9C60AD1b263C37253E7f157231dfF3";
export const Linguo_en_es = "0x5fB4B92c48dB367Dee88e34cA977Af0581D1a855";
export const Linguo_en_fr = "0x81F78a49E472B507B49ea7a01dF2760E1922dce4";
export const Linguo_en_ja = "0x9B926259A16F975f931E5587b5756EFAAC305B5f";
export const Linguo_en_ko = "0x558457cA2a4c22b9A50E8822FDf7927887D90D6c";
export const Linguo_en_pt = "0x3e05C4dEc668bd0A93668437577fea36Db77AB65";
export const Linguo_en_ru = "0xa0D5931DecB5Fb7265ac0417fDB6D2C39500F824";
export const Linguo_en_tr = "0x1bfEbB574A263D4d627ceF63d9fA23CD624E0e5c";
export const Linguo_en_zh = "0x5bd640A53E2E29984D405FCc0b1526c252A325D7";
