name: Deploy Subgraph

on:
  workflow_dispatch:
    inputs:
      network:
        description: The network to deploy the subgraph to
        required: true
        default: 'goerli'
        type: choice
        options:
          - goerli
          - gnosis
      subgraph_name:
        description: The subgraph project name including account name and project id
        default: account/linguo-goerli
        required: true
      environment:
        description: 'The environment to deploy to'
        type: environment
        required: true

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Build and deploy subgraph
        run: |
          export NETWORK_NAME=${{ inputs.network }}
          yarn build:prepare
          yarn build

      - name: Authenticate with TheGraph
        run: yarn auth "${{ secrets.SUBGRAPH_AUTH_TOKEN }}"

      - name: Build and deploy subgraph
        run: |
          yarn graph deploy \
            --product hosted-service \
            --network "${{ inputs.network }}" \
            ${{ inputs.subgraph_name }}
        
