name: Deploy Subgraph

on:
  push:
    branches:
      - master
      - feat/deploy-automation
  workflow_dispatch:
    inputs:
      network:
        description: The network to deploy the subgraph to
        required: true
      subgraph_name:
        description: The subgrap project name including account name and project id
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUBGRAPH_AUTH_TOKEN: ${{ secrets.SUBGRAPH_AUTH_TOKEN }}
      PRODUCTION_NETWORKS: ${{ env.PRODUCTION_NETWORKS }}
      TESTNET_NETWORKS: ${{ env.TESTNET_NETWORKS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Build and deploy subgraph
        run: ./scripts/deploy.sh --n ${{ inputs.network }} --s ${{inputs.subgraph_name}}
